Merged from staging branch: Build version 0.1.232

diff --git a/paulgobero_com/Jenkinsfile b/paulgobero_com/Jenkinsfile
--- a/paulgobero_com/Jenkinsfile
+++ b/paulgobero_com/Jenkinsfile
@@ -64,21 +64,110 @@ pipeline {
 			}
 		}
 
-		stage('2. Run unit Tests') {
-			//Execute if its the staging branch
+		/*stage('Merge and Test') {
+			agent {
+				label 'testnode'
+			}
+            when {
+                branch 'development' // Trigger this stage only for the development branch
+            }
+            steps {
+                // Perform a dry run merge
+                //sh 'git merge --no-commit origin/feature-branch'
+
+                // Start the required services defined in the Docker Compose file
+                sh 'docker-compose -f ./paulgobero_com/testdocker-compose.yml up -d'
+
+                // Run the tests inside the Docker container
+				sh 'docker-compose -f ./paulgobero_com/testdocker-compose.yml exec -T testapp npm run test:unit-inside-docker'
+
+                // Capture the exit code of the tests
+                script {
+                    def testExitCode = sh script: 'docker-compose -f docker-compose.test.yml exec testapp bash -c "echo $?"', returnStatus: true
+                    if (testExitCode != 0) {
+                        echo "Tests failed. Reverted the changes."
+                        // Reverse the merge if tests failed
+                        sh 'git reset --hard HEAD@{1}'
+                        // Push the changes back to the development branch to revert the merge
+                        sh 'git push --force origin development'
+                        currentBuild.result = 'FAILURE' // Mark the build as failed
+                    }
+                }
+
+                // Stop and remove the containers after the tests
+                sh 'docker-compose -f ./paulgobero_com/testdocker-compose.yml down'
+            }
+        }*/
+
+		/*stage('2. Run unit Tests') {
+			environment {
+				HOME = "${WORKSPACE}"
+			}
+			//Execute tests if its development branch
 			when {
-				branch 'staging'
+				branch 'development'
 			}
 			//execute the code on the testing machine
+			agent {
+				docker {
+					image 'paulgl721/jestpuppeteer:1.0'
+				}
+			}
+			steps {
+				echo '..................Runing Tests................'
+				//run tests on the code
+				echo "Testing the code in the git repository"
+				sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/test-step.sh'
+				sh ''' ./${BASE_DIRECTORY}/jenkins-scripts/test-step.sh '''
+				//sh ''' cd ./${BASE_DIRECTORY} '''
+				//sh 'npm install --include dev --prefix ./${BASE_DIRECTORY}'
+				//sh 'npm --prefix ./${BASE_DIRECTORY} run test '
+			}
+		}*/
+
+		stage('2. Run unit Tests') {
+			//Execute tests if its development branch
+			when {
+				branch 'development'
+			}
+			//use jenkins testing node
 			agent {
 				label 'testnode'
 			}
 			steps {
 				echo '..................Runing Tests................'
-				//test code
-				echo "Testing the code in the git repository"
+				withEnv(["ENV_FILE_PATH=/mnt/portfolio/envConfigs/.env.test"]) {
+					// Print the contents of the .env.test file (for verification purposes)
+					sh "cat $ENV_FILE_PATH"
+					//run tests on the code
+					echo "Testing the code in the git repository"
+					sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/test-step.sh'
+					sh ''' ./${BASE_DIRECTORY}/jenkins-scripts/test-step.sh '''
+				}
 			}
 		}
+
+		/*stage('2. Run unit Tests') {
+			environment {
+				HOME = "${WORKSPACE}"
+			}
+			//Execute if its the staging branch
+			when {
+				branch 'development'
+			}
+			//execute the code on the testing machine
+			agent {
+				docker {
+					image 'browserless/chrome'
+				}
+			}
+			steps {
+				echo '..................Runing Tests................'
+				//run tests on the code
+				echo "Testing the code in the git repository"
+				sh 'npm run test'
+			}
+		}*/
 
 		stage('3. Build and taged staging image') {
 			//Execute if its the staging branch
