Merged from development branch: Build version 2.4.348

diff --git a/paulgobero_com/Jenkinsfile b/paulgobero_com/Jenkinsfile
--- a/paulgobero_com/Jenkinsfile
+++ b/paulgobero_com/Jenkinsfile
@@ -4,12 +4,13 @@ def staged_files
 def prod_staged_files
 
 pipeline {
-	//run on different agents
+	//run script on different agents
 	agent none
+	
 
-	//define env variables
+	//reusable env variables
 	environment {
-		VERSION="0.1.${BUILD_NUMBER}"
+		VERSION="2.4.${BUILD_NUMBER}"
 		BASE_DIRECTORY='paulgobero_com'
 		REMOTE_USER='deployuser1'
 		REMOTE_DIR='STAGE_PORTFOLIO'
@@ -17,12 +18,69 @@ pipeline {
 		STACKNAME='stagingportfolio'
 		GIT_REPO='git@github.com:Paul-GL721/portfolio.git'
 		GH_TOKENCRED=credentials('jenkins-post-pr-portfolio')
-		EMAIL_TO='team@paulgobero.com'
+		EMAIL_TO='portfolioteam@paulgobero.com'
 	}
 
 	stages {
-		stage('1. Merge development and staging branches') {
-			//Execute if develpment branch
+		stage('1. Run unit Tests') {
+			//Execute tests if its development branch
+			when {
+				branch 'development'
+			}
+			
+			//use jenkins testing node
+			agent {
+				label 'buildnode'
+			}
+
+			environment {
+                // Set the ENV_FILE_PATH environment variable based on Jenkins workspace
+                ENV_FILE_PATH = "/glustervol/portfolio/paulgobero/configs/.env.test" 
+            }
+			
+			steps {
+				sshagent (credentials: ['e833b0c8-199a-4d54-a272-a021d20c622b']) {
+					// Fetch the latest state of the remote branches
+					sh "git config --global user.email 'lwangapaul23@gmail.com'"
+					sh "git config --global user.name 'jenkinsagent2'"
+					sh 'git fetch origin'
+					// Perform a dry run merge
+					sh 'git merge --no-commit origin/development'
+
+					// Check if the merge was successful
+					script {
+						def mergeExitCode = sh script: 'git ls-files --unmerged | wc -l', returnStatus: true
+						if (mergeExitCode == 0) {
+							// Start the required services defined in the Docker Compose file
+							sh "docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml build"
+							sh 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml up -d'
+
+							// Capture the exit code of the tests
+							def testExitCode = sh(script: 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml exec -T testapp bash -c "echo $?"', returnStatus: true)
+
+							//def testExitCode = sh script: 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml exec -T testapp bash -c "echo $?"', returnStatus: true
+							if (testExitCode != 0) {
+								echo "Tests failed. Reverted the changes."
+								// Reverse the merge if tests failed
+								sh 'git reset --hard HEAD@{1}'
+								// Push the changes back to the development branch to revert the merge
+								sh 'git push --force origin development'
+								currentBuild.result = 'FAILURE' // Mark the build as failed
+							}
+
+							// Stop and remove the containers after the tests
+							sh 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml down'
+						} else {
+							echo "Merge failed. Please resolve conflicts and try again."
+							currentBuild.result = 'FAILURE' // Mark the build as failed
+						}
+					}
+				}
+			}
+		}
+
+		stage('2. Merge development and staging branches') {
+			//Execute if its the develpment branch
 			when {
 				branch 'development'
 			}
@@ -32,7 +90,6 @@ pipeline {
 			}
 			steps {
 				echo '..................Merging if anyfiles have changed................'
-				
 				//with github credentials stored in jenkins server
 				sshagent (credentials: ['e833b0c8-199a-4d54-a272-a021d20c622b']) {
 					script {
@@ -46,7 +103,7 @@ pipeline {
 						sh('git pull')
 						sh('git push ${GIT_REPO}')*/
 
-						//Find the number of staged files
+						//Find the number of staged files 
 						staged_files = sh(script: 'git diff --cached --numstat | wc -l', returnStdout: true) as Integer
 
 						//if staged_files are more than zero, commit the files and push to remote repo
@@ -63,23 +120,7 @@ pipeline {
 			}
 		}
 
-		stage('2. Run unit Tests') {
-			//Execute if its the staging branch
-			when {
-				branch 'staging'
-			}
-			//execute the code on the testing machine
-			agent {
-				label 'testnode'
-			}
-			steps {
-				echo '..................Runing Tests................'
-				//test code
-				echo "Testing the code in the git repository"
-			}
-		}
-
-		stage('3. Build and taged staging image') {
+		stage('3. Build and tag staging image') {
 			//Execute if its the staging branch
 			when {
 				branch 'staging'
@@ -127,15 +168,11 @@ pipeline {
 			//build the docker image and push to dockerhub
 			agent any
 			steps {
-<<<<<<< HEAD
-				echo '..........Would you like to create a Pull Request to Production?........'
-=======
 <<<<<<< .merge_file_a02288
 				echo '..........Would you like to create a Pull Request to Production?........'
 =======
 				echo '................Would you like to create a Pull Request?....................'
 >>>>>>> .merge_file_a16604
->>>>>>> 905d6d3af8a131aea5c277344227be59c3a69517
 				input 'would you like to create a pull request?'
 				
 			}
@@ -161,6 +198,7 @@ pipeline {
 
 						//build the image
 						sh '''./${BASE_DIRECTORY}/jenkins-scripts/merge-code-step.sh '''
+<<<<<<< .merge_file_a02288
 
 						/*//Uncomment if they are changes made and commited to the production branch directly
 						sh('git stash')
@@ -201,8 +239,6 @@ pipeline {
 						echo '..............Creating temporary pull request branch................'
 						echo 'Creating temp branch'
 
-<<<<<<< HEAD
-=======
 =======
 
 						/*//Uncomment if they are changes made and commited to the production branch directly
@@ -245,7 +281,6 @@ pipeline {
 						echo 'Creating temp branch'
 
 >>>>>>> .merge_file_a16604
->>>>>>> 905d6d3af8a131aea5c277344227be59c3a69517
 						//make the pr-branch executable
 						sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/pr-branches.sh'
 
@@ -271,10 +306,7 @@ pipeline {
 					//login, check githubcli pr status, create message and logout
 					sh 'gh --version'					
 					sh 'echo \$GH_TOKENCRED_PSW|gh auth login --hostname github.com --with-token'
-<<<<<<< HEAD
 					//sh 'echo $GH_TOKENCRED_PSW | gh auth login --hostname github.com --with-token'
-=======
->>>>>>> 905d6d3af8a131aea5c277344227be59c3a69517
 					sh 'gh auth status'					
 					echo '.............Creating pull request on master branch..........'
 					sh 'gh pr create --title "Production branch v$VERSION was successful" --body "Production branch version$VERSION was successfully tested and deployed; needs to be merged into master" --base master --head tmpproductionV$VERSION'					
@@ -289,15 +321,11 @@ pipeline {
 				REMOTE_DIR='PORTFOLIO'
 				STACKNAME='portfolio'
 			}
-<<<<<<< HEAD
-			///Execute if its the production branch
-=======
 <<<<<<< .merge_file_a02288
 			///Execute if its the production branch
 =======
 			//Execute if its the production branch
 >>>>>>> .merge_file_a16604
->>>>>>> 905d6d3af8a131aea5c277344227be59c3a69517
 			when {
 				branch 'master'
 			}
@@ -318,13 +346,10 @@ pipeline {
 			}
 		}
 
-<<<<<<< HEAD
-=======
 <<<<<<< .merge_file_a02288
 =======
 
 >>>>>>> .merge_file_a16604
->>>>>>> 905d6d3af8a131aea5c277344227be59c3a69517
 		stage('10. Deploy to production EC2 instance') {
 			//define env variables
 			environment {
@@ -349,10 +374,7 @@ pipeline {
 		}
 	}
 
-<<<<<<< HEAD
 
-=======
->>>>>>> 905d6d3af8a131aea5c277344227be59c3a69517
 	post {
 		success {
 			echo '...........JOB EXECUTED SUCCESSFULLY...........'
