updating testing flow

diff --git a/paulgobero_com/Jenkinsfile b/paulgobero_com/Jenkinsfile
--- a/paulgobero_com/Jenkinsfile
+++ b/paulgobero_com/Jenkinsfile
@@ -34,7 +34,44 @@ pipeline {
                 // Set the ENV_FILE_PATH environment variable based on Jenkins workspace
                 ENV_FILE_PATH = "/mnt/portfolio/envConfigs/.env.test" 
             }
-            steps {
+			steps {
+				// Fetch the latest state of the remote branches
+				sh 'git fetch origin'
+
+				// Perform a dry run merge
+				sh 'git merge --no-commit origin/staging'
+
+				// Check if the merge was successful
+				script {
+					def mergeExitCode = sh script: 'git ls-files --unmerged | wc -l', returnStatus: true
+					if (mergeExitCode == 0) {
+						// Start the required services defined in the Docker Compose file
+						sh "docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml build"
+						sh 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml up -d'
+
+						// Run the tests inside the Docker container
+						sh 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml exec -T testapp npm run test:unit-inside-docker'
+
+						// Capture the exit code of the tests
+						def testExitCode = sh script: 'docker-compose -f ./${BASE_DIRECTORY}/testdocker-compose.yml exec -T testapp bash -c "echo $?"', returnStatus: true
+						if (testExitCode != 0) {
+							echo "Tests failed. Reverted the changes."
+							// Reverse the merge if tests failed
+							sh 'git reset --hard HEAD@{1}'
+							// Push the changes back to the development branch to revert the merge
+							sh 'git push --force origin development'
+							currentBuild.result = 'FAILURE' // Mark the build as failed
+						}
+
+						// Stop and remove the containers after the tests
+						sh 'docker-compose -f ./${BASE_DIRECTORY}/Updatestdocker-compose.yml down'
+					} else {
+						echo "Merge failed. Please resolve conflicts and try again."
+						currentBuild.result = 'FAILURE' // Mark the build as failed
+					}
+				}
+			}
+            /*steps {
 				// Perform a dry run merge
 				sh 'git merge --no-commit origin/feature-branch'
                 echo '..................Runing Tests................'
@@ -59,7 +96,7 @@ pipeline {
 				// Stop and remove the containers after the tests
 				sh 'docker-compose -f ./paulgobero_com/testdocker-compose.yml down'
             }
-			/*steps {
+			steps {
 				echo '..................Runing Tests................'
 				withEnv(["ENV_FILE_PATH=/mnt/portfolio/envConfigs/.env.test"]) {
 					// Print the contents of the .env.test file (for verification purposes)
@@ -69,8 +106,8 @@ pipeline {
 					sh 'chmod +x ./${BASE_DIRECTORY}/jenkins-scripts/test-step.sh'
 					sh ''' ./${BASE_DIRECTORY}/jenkins-scripts/test-step.sh '''
 				}
-			}*/
-		}
+			}
+		}*/
 
 		stage('2. Merge development and staging branches') {
 			//Execute if develpment branch
